const ownerList = {
  1: {
    name: "GÖKHAN İNCE-BÜLENT BEY-ŞAHİN BEY-NUH ŞAHİN-MURAT KOMŞU-YAŞAR ELİDOLU-ZEYNEP ELİDOLU",
  },
  2: {
    name: "İLYAS DOĞER-ASYA ÇETİNKAYA-SİNAN SARAÇ-İLYAS SARAÇ-İLYAS ÇİFTÇİ-YAŞAR GÜREŞ-SÜLEYMAN ÖZÇELİK",
  },
  3: {
    name: "SELMAN OCAK-SELMAN OCAK-MURAT HOCA-MURAT HOCA-ŞİFA HOCA-ŞİFA HOCA-AHMET HOCA",
  },
  4: {
    name: "ARİFE KILIÇARSLAN-İLYAS ÖZKOÇAK-ADİL ÖZKOÇAK-NAİM CANKURT-MEHMET AYÇİÇEK-SELMA IŞIK-İBRAHİM ÖZKOÇAK",
  },
  5: {
    name: "GÜLÜZAR ÇITAK-KEREM ÇITAK-HAMDİ ÇITAK-İZZET DEMİR-HİLMİ KOŞTAN-HAKAN DEMİR-ABDULLAH KANAT",
  },
  6: {
    name: "HATİCE KUZAN-NAZIM KUZAN-RAMAZAN KUZAN-SAVAŞ GÜRGİL-SEVGİ ÖZDEMİR-AYŞEMAN AKGÜL-YÜKSEL KANAT",
  },
  7: {
    name: "DÖNDÜ AYÇİÇEK-İBRAHİM AYÇİÇEK-BAYRAM AYÇİÇEK-AYHAN AYÇİÇEK-FATMA TATLILIOĞLU-FADİME YILMAZ-NEVZAT KOŞTAN",
  },
  8: {
    name: "ERDOĞAN FINDIKLI-YILMAZ MUMCU-HASAN İBİ-MUZAFFER HAZIR-TUNCAY DURUSOY-ÖMER DURUSOY-CENGİZ TOPUZ",
  },
  9: { name: "ZÜLKİF KAYA" },
  10: {
    name: "ALİ MEŞE-YASİN MEŞE-ERDAL MEŞE-NASUH BURGAN-MEMİŞ ÇİLEK-YUNUS MEŞE-SANİYE BURGAN",
  },
  11: {
    name: "HASAN TARHAN-ÖMER KARAPINAR-TAHSİN ARKAÇ-ALİ ACAR-KAZIM GÜRLEK-SURİ GÜRLEK-EVAN SEVİMLİ",
  },
  12: {
    name: "HALİME ÇADIRCI-GÜNSEL BİLBE-FARUK OLGAÇ-KADİR KENAN-SEZER AYDOĞDU-YASİN ESER-SUAT KILINÇ",
  },
  13: {
    name: "YILMAZ TÜRK-AYŞE DOĞAN-YAVUZ ÖZEN-BİLAL KARACA-FİRDEVS GÜLMÜŞ-MUSTAFA EKEN-HAMİDE DOĞAN",
  },
  14: {
    name: "MURAT OLGAÇ-RAMAZAN OLGAÇ-MUSTAFA KAYLAK-SAMET PERDECİ-MUHAMMED ÇETİN-GÖKHAN ÇELİK-DENİZ KURUDERE",
  },
  15: {
    name: "REYHAN CEYHAN-FATİH CEYHAN-ŞERİF CEYHAN-İDRİS CEYHAN-KAZIM CEYHAN-UFUK BABÜR-NECİBE YILMAZ",
  },
  16: { name: "SALİM ER-" },
  17: {
    name: "MEHMET FİLİZ-MEHMET FİLİZ-ARİF ARMUTÇU-İBRAHİM TEKİNDAR-FARUK TEKİNDAR-OSMAN KOÇAK-YUNUS BEKTAŞ",
  },
  18: {
    name: "İRFAN KURUDERE-AHMET ERDOĞAN-KAZIM MEYDANAL-MAFİZ ÇAĞINDA-OLCAY ÇAĞINDA-HAMİT NUSRET YÜZER-ÖMER YALÇIN",
  },
  19: { name: "OSMAN TAMİR-" },
  20: { name: "MUSTAFA KOCABAY-" },
  21: {
    name: "MÜNİR AYŞEN-ADNAN KAYLAK-MUSTAFA KAYLAK-ZEKERİYA ORHAN-ZEKERİYA ORHAN-MEHMET YILMAZ-BURAK YILMAZ",
  },
  22: {
    name: "YAŞAR BULUT-HİKMET ERGENÇ-ALİ KUŞ-ŞENOL KARA-ŞENOL KARA-FİKRET GÖRGÜN-EMRAH EVİRGEN",
  },
  23: {
    name: "YUSUF PEKER-SURURİ PEKER-DURMUŞ DEMİR-MUHLİS BAYSAL-MÜBEYYİN BAYSAL-SELÇUK KONUK-TÜLİN UZUNER",
  },
  24: {
    name: "MAHMUT ÇOLAK-OSMAN ÇOLAK-HAMİT TANRIVER-AYŞEGÜL BAYRAKTAR (AYKUT)-DENİZ BAYRAKTAR(MUSTAFA)-GAMZE BAYRAKTAR(UĞUR)-YAKUP BAYRAKTAR",
  },
  25: {
    name: "MEHMET AKŞEHİRLİ-YILDIZ GÜRSEL-SEDAT KALAYCI-HÜDAYİ DURAN-YUNUS YÜKSEL-MUHAMMET DEMİR-HİKMET IŞIK",
  },
  26: {
    name: "ÜLFET AYHAN-ÜLFET AYHAN-ÜLFET AYHAN-SAİM BAŞAL-MEHMET BAŞAL-NECDET KAYNAK-ÖZKAN KOÇAK",
  },
  27: {
    name: "SEMİH ÇELİK-BAHRİYE TEKİN-ZEYNEP KÖKLÜ-ORHAN YILDIRIM-ORHAN YILDIRIM-ORHAN YILDIRIM-ORHAN YILDIRIM",
  },
  28: {
    name: "ALİ KEMAL AYDIN-AHMET HÜSEYİN AYDIN-GÜLSÜM AYDIN-AHMET AYDIN-BEKİR AYDIN-ŞÜKRÜ ÇİFÇİ",
  },
  29: {
    name: "CEMAL ÜNAL-AYFER SEMERDAN-ENGİN BAYKARA-MEHMET KAŞIKÇI-OLCAY AKDOĞAN-SEYFETTİN DURMUŞ-SAMİ SAMİRA",
  },
  30: {
    name: "HATİCE KOCATAŞ-HALİME KOCATAŞ-SALİH ÇAKMAK-SAVAŞ ÇANAK-HASAN ÇANAK-ALİ CANDEMİR-FERHAN YARGIÇ",
  },
  31: {
    name: "İLHAMİ TAŞDELEN-BÜNYAMİN TAŞDELEN-ZAFER KATI-YAKUP ÇEVİK-YUSUF ÇEVİK-OĞUZHAN ÇEVİK-İSMAİL ERGEN",
  },
  32: {
    name: "YASEMİN ENCİ-EMİRHAN ERÇOBAN-RAHMAN RULMAN-YAHYA ÇİFTÇİ-ABDULLAH SARI-YAŞAR ARSLAN-ÜNAL EROĞLU",
  },
  33: {
    name: "EROL BİÇER-MELEHAT KISA-SAVAŞ SÜLÜNOĞLU-UĞUR KAR-SEFANUR KAR-SATILMIŞ YILDIRIM-BAYRAM ERK",
  },
  34: {
    name: "ZEKİ BAKKAL-ELİF ATAN-SEYHAN ÖZTÜRK-HALİT YAY-HACI YAY-SÜLEYMAN DEMİRSAĞ-HAKAN ORUÇ",
  },
  35: {
    name: "HAKAN ÇETİN -GÜLTEN ÇEVİK-ÜLKER TUNCEL-ELİF ARSLAN-ÖMER KÖSEOĞLU-ESENGÜL KARABULUT-ERDAL PINAR",
  },
  36: {
    name: "NESRİN GÜLEÇ-FADİME GÜLEÇ-ZEKAİ KÖSEOĞLU-ÖMER KÖSEOĞLU-SONER AHİ-EMRAH AHİ-HASAN KOTAŞ",
  },
  37: {
    name: "MAHİR KAPLAN-MEHMET ÇİZMECİ-TALHA YILDIZ-ERHAN ÖZTÜRK-FAHRİ POLAT-SALİH AYDEMİR-HÜSEYİN BOZDAĞ",
  },
  38: {
    name: "NUR HANIM-GÜL HANIM-AHMET GÖKÇE-RAMAZAN ŞAHAN-NURULLAH DEMİR-HÜLYA ÖZDAMAR-KAMİL GÜMÜŞ",
  },
  39: {
    name: "GÜLER YÜCE-FATMA YÜCE-MERYEM TUĞRUL-EKREM YILMAZ-MUAMMER YILMAZ-ABDULLAH YÜCE-İSMAİL KESKİN",
  },
  40: {
    name: "İBRAHİM ARIKAN-HATİCE ARIKAN-TARIK OKCAN-HALİT OKCAN-NAMİ ERTEN-ZEYNEP ERTEN-OSMAN DANIŞMAN",
  },
  41: {
    name: "MEHMET ERTEN-İBRAHİM ACAR-HAMZA YİĞİTARSLAN-SERDAR YILMAZ-SEMİH CAN KARAPINAR-NECATİ KARAPINAR-İSLAM BEY",
  },
  42: {
    name: "KASIM GÜLTEKİN-ALİ ŞEN-KENAN DURUYÜREK-SERPİL DURUYÜREK-ERGÜN CAN-HASAN ÜNAL-ZAHİDE ÜNSAL",
  },
  43: {
    name: "HALİL İBRAHİM GÜNDOĞAN-HALİL İBRAHİM GÜNDOĞAN-HALİL İBRAHİM GÜNDOĞAN-HALİL İBRAHİM GÜNDOĞAN-HALİL İBRAHİM GÜNDOĞAN-HALİL İBRAHİM GÜNDOĞAN",
  },
  44: {
    name: "KADİR TERCAN-ALİ OSMAN TERCAN-ALİ İHSAN YARGIÇ-MUSTAFA YARGIÇ-GÜLSEN YARGIÇ-SEVAL YARGIÇ-BİLSEN VARDAR",
  },
  45: {
    name: "GÖKHAN ÜLKER-FADİME ÜLKER-AYŞE KÖSEOĞLU-FERİHA ÇIBIK-SEFA DEMİR-AHMET KIZRAK-ZİYA ERDOĞAN",
  },
  46: {
    name: "ZUHAL ÜNLÜ-HAKAN ÜNLÜ-MAKSUDE DEMİR-HAMDİYE APAYDIN-LOKMAN ÇANKAYA-RUKİYE BAYKARA-MEHMET DURMUŞ",
  },
  47: {
    name: "ALİ SU-SALİH H. GÖKSU-FATMA YÜKSEL-AYŞE YÜKSEL-HASAN ÇAM-SAMET ÇAM-ZÜBEYDE OTCU",
  },
  48: {
    name: "NUMAN GÜNEY-BERAT ÇEVİK-ADEM ERKMEN-ADEM ERKMEN-ÖZGÜN ÖZEN-MÜNEVVER AYBEL-FEHMİ MEYDANAL",
  },
  49: {
    name: "SEMRA ÖZTÜRK-DURAN YÜKSEL-HASAN KURU-H. HÜSEYİN AYAZ-ZİYA GÜNDOĞDU-EYÜP KOÇYİĞİT-MÜNEVVER YÜKSEL",
  },
  50: {
    name: "ERDAL YÜKSEL-ÇETİN YILMAZ-MURAT ALAN-HEDİYE ALAN-HALİME DURAN-NİLÜFER DURAN-FATİH YÜKSEL",
  },
  51: {
    name: "TEVFİK DEMİR-HİDAYET DOĞAN-EMİN BAYAR-FADİME BAYAR-FERHAT BERİK-NİHAT DOĞAN-AZİZ CÜCÜK",
  },
  52: {
    name: "ŞABAN YAKUT-ARİF MEŞE-CAFER YILDIRIM-MEDİNE ERK-MUSTAFA YAVUZ-RASİM ÇEVİK-RASİM ÇEVİK",
  },
  53: {
    name: "FATMA TOPAL-DURSUNE DEMİR-VAHİT ŞAKAR-İBRAHİM DEMİR-İSMAİL ÖZKAN-ERSİN ÖZKAN-SALİH DOKUMACI",
  },
  54: {
    name: "HAYDAR GÜNEY-HAVVA SAFRAN-DÖNE TOPAL-FATİH KOYUNCU-ZÜLFÜ KOYUNCU-MESUT ERDEM-BÜLENT ÇAVUŞOĞLU",
  },
  55: {
    name: "ERSİN ERTUĞRUL-MEHMET ERTUĞRUL-HADİ SOYLU-MURAT ZENGİN-NİLÜFER AKAR-İBRAHİM ŞENEL-SATILMIŞ BAĞLAN",
  },
  56: {
    name: "İZZET AKBAŞ-HÜSEYİN ÇALIŞKAN-FATMA ERTEN-ÜMİT GÖKÇE-HAYRETTİN GEREDELİOĞLU-İSMAİL TUNCEL-LEYLA TUNCEL",
  },
  57: {
    name: "FİKRET KARAMAN-MERYEM ELMACIOĞLU-SAMİ YILDIZLI-ZEKİ GÜNEŞ-AYHAN SARIKAYA-SEYFİ BAYAR-FATMA BAYAR",
  },
  58: {
    name: "MUSTAFA PABUÇÇU-SİNAN KAYA-ALİ AYAZAL-AYŞE KUŞ-ADEM POLAT-FİDAN DEMİR-YUNUS BAYRAKTAR",
  },
  59: {
    name: "VELİ KESER-FERİDE ULUDAĞ-MEHMET DURMUŞ-GÜL VARLI-MURAT TURAN-MUHAMMED AÇIKGÖZ-MERYEM YARGIÇ",
  },
  60: {
    name: "ZEKERİYA ERİKLİOĞLU-HATİCE ERİKLİOĞLU-MUSTAFA ERİKLİOĞLU-FEYZA ERİKLİOĞLU-TUNAHAN ERİKLİOĞLU-BEDİA ERİKLİOĞLU-FEVZİYE KÖSEOĞLU",
  },
  61: {
    name: "MAKSÜDE UÇAR-SERHAT DEMİRBAĞ-SERHAT DEMİRBAĞ-ALİ IŞIK-CENGİZHAN VARLI-TALİP AKKAYA-ALİ SARI",
  },
  62: {
    name: "NAHİT KICIK-HASAN TEKİN-AYŞE DUDU TEKİN-ADEM TEKİN-ADEM TEKİN-ŞEHRİ DOĞRUSÖZ-HÜSEYİN SOYAL",
  },
  63: {
    name: "SERTAN ÇİMEN-NURETTİN AKKUL-MÜZDELİFE AKKUL-BEKİR ÖZER-HACI GÜLER-GÜLSEREN COŞKUN-GÜNFERİ ÇAKMAK",
  },
  64: {
    name: "NABİ OĞUZ-OSMAN OĞUZ-HALİL KARHAN-SEVGİ KIZILKAYA-AYŞE GÜNEŞ-İFRAN ERYILMAZ-GÜLHANIM ERYILMAZ",
  },
  65: {
    name: "NUH KALELİ-RAZİYE KALELİ-CAVİDE KALELİ-MEHMET CANER-ÖZGÜR DÖRDOĞAN-İSMAİL ERGİN-HALİL İBRAHİM ERGİN",
  },
  66: {
    name: "MURAT ÇAKMAKÇI-FATMA KILIÇ-MUHARREM MÜEZZİNOĞLU-UYGUN KAHVECİ-BEYHAN KAHVECİ-ALİ BİÇER-SELÇUK ATAŞ",
  },
  67: {
    name: "HALİL İBRAHİM BAĞCI-EMİNE BAĞCI-GÜRSEL YILDIRIM-SALİM KUŞ-AKİF ÜNAL-MEHMET ER-MUZAFFER ULAŞ",
  },
  68: {
    name: "BURHAN SAKARYA-BEHSAT YALÇIN-SEBAHAT KARAKAYA-ABDULLAH ÖZCAN-MEHMET AÇIKGÖZ-HİMMET ÜNAL-NURETTİN KÖSE",
  },
  69: {
    name: "ŞAMİL KÖK-ORHAN CANIBEK-HIZIR KAYA-SELAMİ GÜMÜŞ-NECMETTİN DURMUŞ-KENAN GÜNEY-MEHMET SANİ HANALP",
  },
  70: { name: "NURİYE  HANIM" },
  71: {
    name: "SUAT TOPCU-CANAN TOPCU-MEHTAP TOPCU-NİHAT TOPCU-TENZİLE TOPCU-TAHSİN TOPCU-RAMAZAN GÜRKAN",
  },
  72: {
    name: "SAİM ÇETİN-ZEKAİ DOĞAN-EMİN DORUK-BAYRAM KABASAKAL-DERYA KABASAKAL-MEHMET ÖZMEN-İMDAT DEMİRCİ",
  },
};
